# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pansen', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
