# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('drilldown', models.CharField(editable=False, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='test',
            name='pansen',
            field=models.CharField(editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='foo',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Test'),
        ),
    ]
