# Generated by Django 2.2.12 on 2020-05-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0002_selfref'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfref',
            name='c3',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='selfref',
            name='c4',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='selfref',
            name='c5',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='selfref',
            name='c6',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='selfref',
            name='c7',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='selfref',
            name='c8',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='selfref',
            name='xy',
            field=models.IntegerField(default=0),
        ),
    ]
