# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0003_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('buzzer', models.CharField(editable=False, max_length=32)),
                ('foos', models.ManyToManyField(to='exampleapp.Foo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
