# Generated by Django 2.2.14 on 2020-07-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computedfields', '0002_contributingmodelsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributingmodelsmodel',
            options={'managed': False, 'ordering': ('app_label', 'model'), 'verbose_name': 'Model with contributing ForeignKey Fields', 'verbose_name_plural': 'Models with contributing ForeignKey Fields'},
        ),
    ]
